server:
  port: ${PORT:9393}
management:
  contextPath: /management
  security:
    enabled: false
security:
  basic:
    enabled: false
spring:
  cloud:
    deployer:
      cloudfoundry:
        domain: run.pivotal.io
        org: APJ
        space: staging
        username: tmaki@pivotal.io
        password: xxxx
        services: fleet-demo-redis,fleet-demo-rabbitmq
        skip-ssl-validation: false
        url: https://api.${spring.cloud.deployer.cloudfoundry.domain}
        enable-random-app-name-prefix: true
