server:
  port: ${PORT:9393}
management:
  contextPath: /management
  security:
    enabled: false
security:
  basic:
    enabled: false
spring:
  cloud:
    deployer:
      cloudfoundry:
        domain: apps.pcfdemo.ik.am
        org: fleet-demo
        space: development
        username: demo
        password: demo
        services: fleet-demo-redis,fleet-demo-rabbitmq
        skip-ssl-validation: true
        url: https://api.system.pcfdemo.ik.am
        enable-random-app-name-prefix: false
