server:
  port: ${PORT:9393}
management:
  contextPath: /management
  security:
    enabled: false
security:
  basic:
    enabled: false
spring:
  cloud:
    deployer:
      cloudfoundry:
        domain: 52.68.100.51.xip.io
        org: pcfdev-org
        space: pcfdev-space
        username: admin
        password: admin
        services: fleet-demo-redis,fleet-demo-rabbitmq
        skip-ssl-validation: true
        url: http://api.${spring.cloud.deployer.cloudfoundry.domain}
